import React, { useState } from 'react';
import { PieChart, TrendingUp, Users, DollarSign, Activity, ChevronRight, Award, Download, Share2 } from 'lucide-react';

export const AnalyticsCard = ({ data }) => {
  const [activeTab, setActiveTab] = useState('overview'); // overview, members, financials

  // Add dummy data for more tabs if missing
  const extendedData = {
    ...data,
    monthlyRevenue: [
      { month: 'Jan', val: 32000 },
      { month: 'Feb', val: 35000 },
      { month: 'Mar', val: 34000 },
      { month: 'Apr', val: 38000 },
      { month: 'May', val: 40000 },
      { month: 'Jun', val: 42500 }
    ],
    memberSegments: [
      { label: 'Standard', percentage: 60, color: 'bg-blue-500' },
      { label: 'Premium', percentage: 30, color: 'bg-purple-500' },
      { label: 'VIP', percentage: 10, color: 'bg-yellow-500' }
    ]
  };

  const maxRev = Math.max(...extendedData.monthlyRevenue.map(d => d.val));

  return (
    <div className="bg-sidebar border border-stroke rounded-3xl overflow-hidden shadow-2xl w-full mx-auto my-6 relative transition-all duration-300">
      
      {/* Header */}
      <div className="px-5 py-4 border-b border-stroke flex items-center justify-between bg-sidebar/50">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-full bg-purple-500/10 flex items-center justify-center text-purple-500 shrink-0">
            <PieChart size={16} />
          </div>
          <div>
            <h3 className="text-sm font-bold text-title">System Analytics Report</h3>
            <span className="text-[10px] text-subtitle">Generated by Aura.AI • {data.period || 'Last 30 Days'}</span>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button className="p-2 text-subtitle hover:text-title hover:bg-background rounded-lg transition-colors">
            <Share2 size={14} />
          </button>
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-primary border border-primary/20 bg-primary/5 rounded-lg hover:bg-primary/10 transition-colors">
            <Download size={12} /> Export CSV
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-stroke">
        {['overview', 'financials', 'members'].map((tab) => (
          <button 
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex-1 py-3 text-[11px] font-bold uppercase tracking-wider transition-colors border-b-2 ${activeTab === tab ? 'text-primary border-primary bg-primary/5' : 'text-subtitle border-transparent hover:bg-background'}`}
          >
            {tab}
          </button>
        ))}
      </div>

      <div className="p-5 md:p-6 bg-background/50">
        {activeTab === 'overview' && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 animate-fade-in">
             <div className="bg-background border border-stroke rounded-2xl p-4 flex flex-col gap-2 relative overflow-hidden group">
               <div className="absolute -right-4 -top-4 w-16 h-16 bg-green-500/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
               <div className="text-subtitle flex items-center gap-2 mb-1 relative z-10"><DollarSign size={14} className="text-green-500"/> <span className="text-[10px] font-bold uppercase tracking-wider">Revenue</span></div>
               <div className="text-xl font-bold text-title relative z-10">{extendedData.revenue}</div>
               <div className="text-[11px] font-medium text-green-500 flex items-center gap-1 relative z-10"><TrendingUp size={12}/> {extendedData.revenueGrowth} vs last month</div>
             </div>

             <div className="bg-background border border-stroke rounded-2xl p-4 flex flex-col gap-2 relative overflow-hidden group">
               <div className="absolute -right-4 -top-4 w-16 h-16 bg-blue-500/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
               <div className="text-subtitle flex items-center gap-2 mb-1 relative z-10"><Users size={14} className="text-blue-500"/> <span className="text-[10px] font-bold uppercase tracking-wider">Members</span></div>
               <div className="text-xl font-bold text-title relative z-10">{extendedData.members}</div>
               <div className="text-[11px] font-medium text-green-500 flex items-center gap-1 relative z-10"><TrendingUp size={12}/> {extendedData.membersGrowth} vs last month</div>
             </div>

             <div className="bg-background border border-stroke rounded-2xl p-4 flex flex-col gap-2 relative overflow-hidden group">
               <div className="absolute -right-4 -top-4 w-16 h-16 bg-yellow-500/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
               <div className="text-subtitle flex items-center gap-2 mb-1 relative z-10"><Activity size={14} className="text-yellow-500"/> <span className="text-[10px] font-bold uppercase tracking-wider">Retention</span></div>
               <div className="text-xl font-bold text-title relative z-10">{extendedData.retentionScore}%</div>
               <div className="text-[11px] font-medium text-subtitle relative z-10">Healthy Level</div>
             </div>

             <div className="bg-background border border-stroke rounded-2xl p-4 flex flex-col gap-2 relative overflow-hidden group">
               <div className="absolute -right-4 -top-4 w-16 h-16 bg-purple-500/5 rounded-full group-hover:scale-150 transition-transform duration-500"></div>
               <div className="text-subtitle flex items-center gap-2 mb-1 relative z-10"><Award size={14} className="text-purple-500"/> <span className="text-[10px] font-bold uppercase tracking-wider">Top Trainer</span></div>
               <div className="text-sm font-bold text-title mt-1 relative z-10">{extendedData.topTrainer}</div>
               <div className="text-[11px] font-medium text-purple-400 flex items-center gap-1 relative z-10 cursor-pointer hover:underline">View Profile <ChevronRight size={12}/></div>
             </div>
          </div>
        )}

        {activeTab === 'financials' && (
          <div className="flex flex-col gap-5 animate-fade-in">
             <div className="flex items-center justify-between">
               <div>
                 <h4 className="text-sm font-bold text-title">Revenue Growth</h4>
                 <p className="text-[11px] text-subtitle">Trailing 6 months performance</p>
               </div>
               <div className="text-right">
                 <h4 className="text-lg font-black text-green-500">{extendedData.revenue}</h4>
                 <p className="text-[10px] font-bold text-subtitle uppercase tracking-wider">Current Month</p>
               </div>
             </div>
             
             <div className="h-40 w-full flex items-end justify-between gap-2 pt-4">
               {extendedData.monthlyRevenue.map((dataPoint, idx) => {
                 const heightPct = (dataPoint.val / maxRev) * 100;
                 return (
                   <div key={idx} className="flex flex-col items-center gap-2 flex-1 group">
                     <div className="w-full relative h-full flex items-end justify-center rounded-t-md overflow-hidden bg-sidebar">
                       <div 
                         className="w-full bg-gradient-to-t from-green-500/20 to-green-500/80 rounded-t-md transition-all duration-700 ease-out group-hover:to-green-400"
                         style={{ height: `${heightPct}%` }}
                       ></div>
                       {/* Tooltip on hover */}
                       <div className="absolute top-2 opacity-0 group-hover:opacity-100 transition-opacity text-[10px] font-bold text-white bg-black/80 px-2 py-1 rounded shadow-lg pointer-events-none">
                         ${(dataPoint.val / 1000).toFixed(1)}k
                       </div>
                     </div>
                     <span className="text-[10px] font-bold text-subtitle uppercase">{dataPoint.month}</span>
                   </div>
                 );
               })}
             </div>
          </div>
        )}

        {activeTab === 'members' && (
          <div className="flex flex-col md:flex-row gap-6 animate-fade-in">
            <div className="flex-1 flex flex-col gap-4 justify-center">
              <div>
                 <h4 className="text-sm font-bold text-title">Member Distribution</h4>
                 <p className="text-[11px] text-subtitle">Active subscription tiers</p>
              </div>
              <div className="flex flex-col gap-3">
                {extendedData.memberSegments.map((seg, idx) => (
                  <div key={idx} className="flex flex-col gap-1.5">
                    <div className="flex justify-between text-xs font-bold text-title">
                      <span>{seg.label}</span>
                      <span>{seg.percentage}%</span>
                    </div>
                    <div className="w-full h-2 bg-sidebar rounded-full overflow-hidden">
                      <div className={`h-full ${seg.color} rounded-full`} style={{ width: `${seg.percentage}%` }}></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="flex-1 bg-background border border-stroke rounded-2xl p-4">
               <h4 className="text-xs font-bold text-subtitle uppercase tracking-wider mb-4 border-b border-stroke pb-2">Key Metrics</h4>
               <div className="flex flex-col gap-3">
                 <div className="flex justify-between items-center">
                   <span className="text-sm text-subtitle">Total Active</span>
                   <span className="text-sm font-bold text-title">{extendedData.members}</span>
                 </div>
                 <div className="flex justify-between items-center">
                   <span className="text-sm text-subtitle">Activity Rate</span>
                   <span className="text-sm font-bold text-green-500">{extendedData.activeRate}</span>
                 </div>
                 <div className="flex justify-between items-center">
                   <span className="text-sm text-subtitle">Churn Rate (MoM)</span>
                   <span className="text-sm font-bold text-red-400">2.4%</span>
                 </div>
                 <div className="flex justify-between items-center">
                   <span className="text-sm text-subtitle">Avg. LTV</span>
                   <span className="text-sm font-bold text-title">$850</span>
                 </div>
               </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};
